//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameInventoryAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Genre
    {
        public int GameGenreId { get; set; }
        public int GameId { get; set; }
        public int GenreId { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
